<?php
// Schema for society_onboarding_data table
define('SOCIETY_ONBOARDING_DATA_SCHEMA', [
    ['name' => 'id', 'type' => 'int(11)', 'null' => false, 'key' => 'PRI', 'extra' => 'auto_increment'],
    ['name' => 'client_type_id', 'type' => 'int(11)', 'null' => true, 'key' => 'MUL'],
    ['name' => 'society_name', 'type' => 'varchar(255)', 'null' => false],
    ['name' => 'street_address', 'type' => 'text', 'null' => false],
    ['name' => 'city', 'type' => 'varchar(100)', 'null' => false],
    ['name' => 'district', 'type' => 'varchar(100)', 'null' => false],
    ['name' => 'state', 'type' => 'varchar(100)', 'null' => false],
    ['name' => 'pin_code', 'type' => 'varchar(10)', 'null' => false],
    ['name' => 'gst_number', 'type' => 'varchar(50)', 'null' => true],
    ['name' => 'address', 'type' => 'text', 'null' => false],
    ['name' => 'latitude', 'type' => 'decimal(9,6)', 'null' => false],
    ['name' => 'longitude', 'type' => 'decimal(9,6)', 'null' => false],
    ['name' => 'onboarding_date', 'type' => 'date', 'null' => false],
    ['name' => 'contract_expiry_date', 'type' => 'date', 'null' => true],
    ['name' => 'qr_code', 'type' => 'varchar(255)', 'null' => true],
    ['name' => 'guards', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'guard_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'guard_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'dogs', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'dog_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'dog_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'armed_guards', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'armed_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'armed_guard_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'housekeeping', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'housekeeping_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'housekeeping_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'bouncers', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'bouncer_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'bouncer_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'site_supervisors', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'site_supervisor_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'site_supervisor_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'supervisors', 'type' => 'int(11)', 'null' => true, 'default' => '0'],
    ['name' => 'supervisor_client_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'supervisor_employee_rate', 'type' => 'decimal(10,2)', 'null' => true, 'default' => '0.00'],
    ['name' => 'compliance_status', 'type' => 'tinyint(1)', 'null' => true, 'default' => '0', 'comment' => '0=Non-Compliant, 1=Compliant'],
    ['name' => 'is_gst_applicable', 'type' => 'tinyint(1)', 'null' => true, 'default' => '1', 'comment' => '1=GST Applicable, 0=GST Not Applicable'],
    ['name' => 'created_at', 'type' => 'timestamp', 'null' => true, 'default' => 'current_timestamp()'],
]); 